<a href="https://colab.research.google.com/github/kanish-27/KanishKrishna-Codeboosters-Internship-2026/blob/main/Phase_01_Data_Engineering/Day_05_ML_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
df=pd.read_csv("/content/Housing.csv")

In [45]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [46]:
x=df[['area','bedrooms','bathrooms','stories','parking']]

In [47]:
y=df['price']

In [48]:
df.isnull().any()

price               False
area                False
bedrooms            False
bathrooms           False
stories             False
mainroad            False
guestroom           False
basement            False
hotwaterheating     False
airconditioning     False
parking             False
prefarea            False
furnishingstatus    False
dtype: bool

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [50]:
from sklearn.tree import DecisionTreeRegressor
dt_model=DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)

In [51]:
dt_model.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [52]:
y_predict=dt_model.predict(x_test)

In [53]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("Mean_absolute_error",mean_absolute_error(y_test,y_predict))
print("Mean_Squared_error",mean_squared_error(y_test,y_predict))
print("r2 Score",r2_score(y_test,y_predict))

Mean_absolute_error 1101023.7707780846
Mean_Squared_error 2374235367265.363
r2 Score 0.44777689816013966

In [54]:
from sklearn.ensemble import RandomForestRegressor
rf_model=RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [55]:
rf_model.fit(x_train,y_train)

RandomForestRegressor(random_state=42)

In [56]:
y_predict=rf_model.predict(x_test)

In [57]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("Mean_absolute_error",mean_absolute_error(y_test,y_predict))
print("Mean_Squared_error",mean_squared_error(y_test,y_predict))
print("r2 Score",r2_score(y_test,y_predict))

Mean_absolute_error 1078898.4680428135
Mean_Squared_error 2319778869476.57
r2 Score 0.46044292804870113